# cluster name, cluster count, kubeconfig context
clusters:
  - {name: "", contexts: "", cloud: "", region: "", az: ""}
  - {name: "", contexts: "", cloud: "", region: "", az: ""}
  - {name: "", contexts: "", cloud: "", region: "", az: ""}

# ACM Version
acm_version: 2.4

# AWS credentials set to environment variables:
# AWS_ACCESS_KEY and AWS_SECRET_KEY

# GCP credentials set to environment variables:
# OCP_SERVICE_ACCOUNT
# ex. export OCP_SERVICE_ACCOUNT=$(cat ~/.gcp/osServiceAccount.json)

# Hub context - set to the name of cluster for ACM and hub install
hub_context: 

# OpenShift Container Platform pull secret retreive from --> cloud.redhat.com/openshift/install/pull-secret
# add path where pull secret is located 
ocp_pull_secret_path: 

# ManagedClusterSet Name
clusterset_name: 

# kubectl path
kubectl: 

# Cockroachdb cli path 
cockroach: 

# Application repo for cockroachdb
app_repo: 

### Git variables ###

git_url: 
git_branch: 
git_msg: 'update files with ansible'
git_remove_local: false
git_username: ansible_git
git_email: ansible_git@ansible.com

### Image Registry credentials ###
ir_username: 
# export IR_PASSWORD="$(cat ~/.ir_password)"


### Git credentials ###

# Git ssh environemnt variable need to be set 
# GIT_SSH_COMMAND
# example: GIT_SSH_COMMAND="ssh -i /pathToYour/.ssh/id_rsa"

### Resources ###

# These are the defaults
pod_cpu: "2"
pod_memory: "5Gi"
volumeClaimTemplates_storage: 100Gi