# cluster name, cluster count, kubeconfig context
clusters:
  - {name: gcp-mgmt1, contexts: gcp-mgmt1, cloud: gcp}
  - {name: gcp-mgmt2, contexts: gcp-mgmt2, cloud: gcp}
  # - {name: az-useast-mgmt1, contexts: az-useast-mgmt1, cloud: azure}

# ACM Version
acm_version: 2.4

# Cockroach Version:
cockroachdb_version: "v21.2.2"

# AWS credentials set to environment variables:
# AWS_ACCESS_KEY and AWS_SECRET_KEY

# GCP credentials set to environment variables:
# OCP_SERVICE_ACCOUNT
# ex. export OCP_SERVICE_ACCOUNT=$(cat ~/.gcp/osServiceAccount.json)

# Hub context - set to the name of cluster for ACM and hub install
hub_context: hub

# OpenShift Container Platform pull secret retreive from --> cloud.redhat.com/openshift/install/pull-secret
# add path where pull secret is located 
ocp_pull_secret_path: ~/.pull-secret.json

# ManagedClusterSet Name
clusterset_name: cockroachdb-clusterset

# az path
az: /usr/local/bin/az

# kubectl path
kubectl: /usr/local/bin/kubectl

# Cockroachdb cli path 
cockroach: /usr/local/bin/cockroach

### Git variables ###

git_url: git@github.com:cmwylie19/ansible-multicluster-cockroachdb.git
# This must be main or the ansible-git and git-clean roles will need to be rewritten
git_branch: 'main'
git_msg: 'update files with ansible'
git_remove_local: false
git_username: ansible_git
git_email: ansible_git@ansible.com

### Image Registry credentials ###
ir_username: 
# export IR_PASSWORD="$(cat ~/.ir_password)"


### Git credentials ###

# Git ssh environemnt variable need to be set 
# export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa"
# example: export GIT_SSH_COMMAND="ssh -i /pathToYour/.ssh/id_rsa"

### Resources ###

# These are the defaults
pod_cpu: "2"
pod_memory: "5Gi"
volumeClaimTemplates_storage: 100Gi