# cluster name, cluster count, kubeconfig context
clusters:
  - {name: gcp-us-central-1, contexts: gcp-us-central-1, cloud: gcp, region: us-central-1, az: us-central1-a}
  - {name: aws-us-east-2, contexts: aws-us-east-2, cloud: aws, region: us-east-2, az: us-east-2a}
  - {name: gcp-us-west-1, contexts: gcp-us-west-1, cloud: gcp, region: us-west-1, az: us-west1-a}

# ACM Version
acm_version: 2.4

# Cockroach Version:
cockroachdb_version: "v21.2.2"
# AWS credentials set to environment variables:
# AWS_ACCESS_KEY and AWS_SECRET_KEY

# GCP credentials set to environment variables:
# OCP_SERVICE_ACCOUNT
# ex. export OCP_SERVICE_ACCOUNT=$(cat ~/.gcp/osServiceAccount.json

# Hub context - set to the name of cluster for ACM and hub install
hub_context: hub

# OpenShift Container Platform pull secret retreive from --> cloud.redhat.com/openshift/install/pull-secret
# add path where pull secret is located 
ocp_pull_secret_path: /path/to/pull-secret.json

# ManagedClusterSet Name
clusterset_name: cockroachdb-clusterset

# kubectl path
kubectl: /usr/local/bin/kubectl

# Cockroachdb cli path 
cockroach: /usr/local/bin/cockroach

# Application repo for cockroachdb
app_repo: https://github.com/<your_github_user>/ansible-multicluster-cockroachdb.git

### Git variables ###

git_url: https://github.com/<your_github_user>/ansible-multicluster-cockroachdb.git
git_branch: 'main'
git_msg: 'update files with ansible'
git_remove_local: false
git_username: your_github_user
git_email: ansible_git@ansible.com

### Git credentials ###

# Git ssh environemnt variable need to be set 
# GIT_SSH_COMMAND
# export GIT_SSH_COMMAND="ssh -i /pathToYour/.ssh/id_rsa"

### Resources ###

# These are the defaults

resources:
  # Note that requests and limits should have identical values. ( says cockroachdb in statefulset )

  pod:
    limits:
      cpu: "2"
      memory: "5Gi"
    requests:
      cpu: "2"
      memory: "5Gi"
      
  volumeClaimTemplates:
    resources:
      requests: 
        storage: 100Gi