# cluster name, cluster count, kubeconfig context
# Example 
# clusters:
#   - {name: cluster1, count: "1", contexts: cluster1}
#   - {name: cluster2, count: "2", contexts: cluster2}


# OpenShift Container Platform pull secret retreive from --> cloud.redhat.com/openshift/install/pull-secret
# add .dockerconfigjson as value
ocp_pull_secret: 

# ManagedClusterSet Name
clusterset_name: 

# AWS credentials
aws_access_key_id:
aws_secret_access_key: 