# cluster name, cluster count, kubeconfig context
clusters:
  - {name: "managed-2", contexts: "managed-2", cloud: "on-prem", region: "us-east1", az: "us-east1-a"}
  - {name: "managed-1", contexts: "managed-1", cloud: "on-prem", region: "europe-east1", az: "europe-east1-a"}

# ACM Version
acm_version: 2.4

# Cockroach Version:
cockroachdb_version: "v21.2.2"

# AWS credentials set to environment variables:
# AWS_ACCESS_KEY and AWS_SECRET_KEY

# GCP credentials set to environment variables:
# OCP_SERVICE_ACCOUNT
# ex. export OCP_SERVICE_ACCOUNT=$(cat ~/.gcp/osServiceAccount.json)

# Hub context - set to the name of cluster for ACM and hub install
hub_context: hub

# OpenShift Container Platform pull secret retreive from --> cloud.redhat.com/openshift/install/pull-secret
# add path where pull secret is located 
ocp_pull_secret_path: /Users/cmwylie19/Public/ansible-multicluster-cockroachdb/pull-secret.json

# ManagedClusterSet Name
clusterset_name: cockroachdb-clusterset

# kubectl path
kubectl: /usr/local/bin/kubectl

# Cockroachdb cli path 
cockroach: /usr/local/bin/cockroach

# Application repo for cockroachdb
app_repo: git@github.com:cmwylie19/ansible-multicluster-cockroachdb.git

### Git variables ###

git_url: git@github.com:cmwylie19/ansible-multicluster-cockroachdb.git
git_branch: 'main'
git_msg: 'update files with ansible'
git_remove_local: false
git_username: cmwylie19
git_email: cmwylie19@gmail.com

### Image Registry credentials ###
ir_username: 
# export IR_PASSWORD="$(cat ~/.ir_password)"


### Git credentials ###

# Git ssh environemnt variable need to be set 
# GIT_SSH_COMMAND
# example: export GIT_SSH_COMMAND="$(cat /Users/cmwylie19/.ssh/id_ed25519)"

### Resources ###

# These are the defaults
pod_cpu: "2"
pod_memory: "5Gi"
volumeClaimTemplates_storage: 3Gi