# cluster name, cluster count, kubeconfig context
clusters:
  - {name: cluster1, count: "1", contexts: cluster1}
  - {name: cluster2, count: "2", contexts: cluster2}


# AWS credentials set to environment variables:
# AWS_ACCESS_KEY and AWS_SECRET_KEY

# Hub context - set to the name of cluster for ACM and hub install
hub_context: 

# OpenShift Container Platform pull secret retreive from --> cloud.redhat.com/openshift/install/pull-secret
# add path where pull secret is located 
ocp_pull_secret_path: 

# ManagedClusterSet Name
clusterset_name: 

# kubectl path
kubectl: 

# Cockroachdb cli path 
cockroach: 

# Application repo for cockroachdb
app_repo: 


# Git variables
git_url: 
git_key: 
git_branch: 'master'
git_msg: 'update files with ansible'
git_remove_local: false
git_username: ansible_git
git_email: ansible_git@ansible.com 
