# cluster name, cluster count, kubeconfig context
clusters:
  - {name: gcp-us-central-1, contexts: gcp-us-central-1, cloud: gcp}
  # - {name: aws-us-east-2, contexts: aws-us-east-2, cloud: aws}
  - {name: gcp-us-west-1, contexts: gcp-us-west-1, cloud: gcp}

# Choose cloud to install on gcp or aws
cloud: gcp

# ACM Version
acm_version: 2.3

# GCP User
# discovered by $> gcloud info | grep Account
gcp_user: cwylie@redhat.com

# AWS credentials set to environment variables:
# AWS_ACCESS_KEY and AWS_SECRET_KEY

# GCP credentials set to environment variables:
# OCP_SERVICE_ACCOUNT
# ex. export OCP_SERVICE_ACCOUNT=$(cat sa.json)

# Hub context - set to the name of cluster for ACM and hub install
hub_context: hub

# OpenShift Container Platform pull secret retreive from --> cloud.redhat.com/openshift/install/pull-secret
# add path where pull secret is located 
ocp_pull_secret_path: /Users/cmwylie19/Public/ansible-multicluster-cockroachdb/pull-secret.json

# ManagedClusterSet Name
clusterset_name: cockroachdb-clusterset

# kubectl path
kubectl: /usr/local/bin/kubectl

# Cockroachdb cli path 
cockroach: /usr/local/bin/cockroach

# Application repo for cockroachdb
app_repo: https://github.com/cm891237/ansible-multicluster-cockroachdb.git

### # Git variables ###

git_url: https://github.com/cm891237/ansible-multicluster-cockroachdb.git
git_branch: 'main'
git_msg: 'update files with ansible'
git_remove_local: false
git_username: cm891237
git_email: cm891237@gmail.com

### Git credentials ###

# Git ssh environemnt variable need to be set 
# GIT_SSH_COMMAND
# export GIT_SSH_COMMAND="ssh -i /Users/cmwylie19/.ssh/gh_cm891237"

### Resources ###

pod:
  limits:
    cpu:
    memory:
  requests:
    cpu:
    memory:
pv:
  capacity:
    storage:
pvc:
  resources:
    requests: 
       storage: 