---
- name: set default for state
  set_fact: 
    setState: present
  when: setState is not defined

- name: Create pull secret variable
  set_fact: 
    ocp_pull_secret: "{{ lookup('file', '{{ ocp_pull_secret_path }}') | from_json  }}"

- name: Create namespace for ACM
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state:  "{{ setState }}"
    definition:
      apiVersion: project.openshift.io/v1
      description: hub
      displayName: hub
      kind: Project
      metadata:
          name: hub

- name: Create OpenShift Container Platform pull secret
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    namespace: hub
    state: "{{ setState }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ocp-pull-secret
      data:
        .dockerconfigjson: "{{ ocp_pull_secret | to_json | b64encode }}"
      type: kubernetes.io/dockerconfigjson

- name: Create operator group in hub namespace
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state: "{{ setState }}"
    namespace: hub
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: hub-operator-group
      spec:
        targetNamespaces: 
        - "hub"

- name: Create ACM operator subscription
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state: "{{ setState }}"
    namespace: hub
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: acm-operator-subscription
      spec:
        sourceNamespace: openshift-marketplace
        source: redhat-operators
        channel: release-2.3
        installPlanApproval: Automatic
        name: advanced-cluster-management

- name: Wait till the multicluster-operators-application is created
  kubernetes.core.k8s_info:
    kind: Deployment 
    name: multicluster-operators-application
    namespace: hub
    wait: yes
    context: "{{ hub_context }}"
    wait_sleep: 10
    wait_timeout: 300
    wait_condition:
      type: Available
      status: True

- name: Create MultiClusterHub custom resource
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state: "{{ setState }}"
    namespace: hub
    definition:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: hub
      spec:
        imagePullSecret: ocp-pull-secret