---
# - name: Check amount of clusters
#   include_role:
#     name: install-multi-cockroachdb
#     tasks_from: pre_validation

- name: Create pull secret variable
  set_fact: 
    ocp_pull_secret: "{{ lookup('file', '{{ ocp_pull_secret_path }}') | from_json  }}"

- name: Create namespace for ACM
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state: present
    definition:
      apiVersion: project.openshift.io/v1
      description: "{{ hub_context }}"
      displayName: "{{ hub_context }}"
      kind: Project
      metadata:
          name: "{{ hub_context }}"

- name: Create OpenShift Container Platform pull secret
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    namespace: "{{ hub_context }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ocp-pull-secret
      data:
        .dockerconfigjson: "{{ ocp_pull_secret | to_json | b64encode }}"
      type: kubernetes.io/dockerconfigjson

- name: Create operator group in hub namespace
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state: present
    namespace: "{{ hub_context }}"
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: hub-operator-group
      spec:
        targetNamespaces: 
        - "{{ hub_context }}"

- name: Create ACM operator subscription
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state: present
    namespace: "{{ hub_context }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: acm-operator-subscription
      spec:
        sourceNamespace: openshift-marketplace
        source: redhat-operators
        channel: "release-{{ acm_version }}"
        installPlanApproval: Automatic
        name: advanced-cluster-management

- name: Wait till the multicluster-operators-standalone-subscription is created
  kubernetes.core.k8s_info:
    kind: Deployment 
    name: multicluster-operators-standalone-subscription
    wait: yes
    context: "{{ hub_context }}"
    wait_sleep: 10
    wait_timeout: 300
    wait_condition:
      type: Available
      status: True
  register: operator_ready

- name: Create MultiClusterHub custom resource
  kubernetes.core.k8s:
    wait: yes
    context: "{{ hub_context }}"
    state: present
    namespace: "{{ hub_context }}"
    definition:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: "{{ hub_context }}"
      spec:
        imagePullSecret: ocp-pull-secret
        disableHubSelfManagement: true
