---
- name: Uninstall Everything
  hosts: localhost
  gather_facts: false

  roles:
    - remove-submar-addon
    - remove-clusterset
    - remove-imported-clusters
    - uninstall-acm

# start_time=`date +%s`
# ansible-playbook delete-all.yml
# end_time=`date +%s`
# echo execution time was `expr $end_time - $start_time` s.
# say `expr $end_time - $start_time` seconds