---
- name: Install of ACM, import clusters, clustersets, submariner-addon, multi-cockroachdb deployment
  hosts: localhost
  gather_facts: false

  roles:
    - install-acm
    - import-clusters
    - create-clusterset
    - install-submar-addon
    - install-multi-cockroachdb

# start_time=`date +%s`
# ansible-playbook install-all.yml
# end_time=`date +%s`
# echo execution time was `expr $end_time - $start_time` s.
# say `expr $end_time - $start_time` seconds