apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.open-cluster-management.io/v1","kind":"Klusterlet","metadata":{"annotations":{},"name":"klusterlet"},"spec":{"clusterName":"ansible-managed-1","namespace":"open-cluster-management-agent","registrationImagePullSpec":"registry.redhat.io/rhacm2/registration-rhel8@sha256:11ebc9839a641f2d89f55e215112b5fd970d2159c581d05e164049656c2f3803","workImagePullSpec":"registry.redhat.io/rhacm2/work-rhel8@sha256:8b34854adfa747bdecf2352933b30d4a98b799a98022074388ea08970da0f80c"}}
  creationTimestamp: "2021-12-06T19:55:38Z"
  finalizers:
  - operator.open-cluster-management.io/klusterlet-cleanup
  generation: 1
  name: klusterlet
  resourceVersion: "32331"
  uid: e5be79bb-792d-48c6-845a-7b0908eb4461
spec:
  clusterName: ansible-managed-1
  namespace: open-cluster-management-agent
  registrationImagePullSpec: registry.redhat.io/rhacm2/registration-rhel8@sha256:11ebc9839a641f2d89f55e215112b5fd970d2159c581d05e164049656c2f3803
  workImagePullSpec: registry.redhat.io/rhacm2/work-rhel8@sha256:8b34854adfa747bdecf2352933b30d4a98b799a98022074388ea08970da0f80c
status:
  conditions:
  - lastTransitionTime: "2021-12-06T19:55:50Z"
    message: |-
      Failed to create &SelfSubjectAccessReview{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:SelfSubjectAccessReviewSpec{ResourceAttributes:&ResourceAttributes{Namespace:,Verb:create,Group:cluster.open-cluster-management.io,Version:,Resource:managedclusters,Subresource:,Name:,},NonResourceAttributes:nil,},Status:SubjectAccessReviewStatus{Allowed:false,Reason:,EvaluationError:,Denied:false,},} with bootstrap secret "open-cluster-management-agent" "bootstrap-hub-kubeconfig": Post "https://api.acm-hub-cwylie.fsi-env2.rhecoeng.com:6443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")
      Failed to get kubeconfig from `kubectl get secret -n "open-cluster-management-agent" "hub-kubeconfig-secret" -ojsonpath='{.data.kubeconfig}'`. This is set by the klusterlet registration deployment, but the CSR must be approved by the cluster-admin on the hub.
    reason: BootstrapSecretError,HubKubeConfigMissing
    status: "True"
    type: KlusterletRegistrationDegraded
  - lastTransitionTime: "2021-12-06T19:55:50Z"
    message: |-
      Failed to get kubeconfig from `kubectl get secret -n "open-cluster-management-agent" "hub-kubeconfig-secret" -ojsonpath='{.data.kubeconfig}'`. This is set by the klusterlet registration deployment, but the CSR must be approved by the cluster-admin on the hub.
      1 of requested instances are unavailable of deployment "open-cluster-management-agent" "klusterlet-work-agent"
    reason: HubKubeConfigMissing,UnavailablePods
    status: "True"
    type: KlusterletWorkDegraded
  - lastTransitionTime: "2021-12-06T19:55:52Z"
    message: Klusterlet Component Applied
    reason: KlusterletApplied
    status: "True"
    type: Applied
  generations:
  - group: apps
    lastGeneration: 1
    name: klusterlet-registration-agent
    namespace: open-cluster-management-agent
    resource: deployments
    version: v1
  - group: apps
    lastGeneration: 1
    name: klusterlet-work-agent
    namespace: open-cluster-management-agent
    resource: deployments
    version: v1
  observedGeneration: 1



--- 
TASK [install-acm : Create MultiClusterHub custom resource] *************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "error": 500, "msg": "MultiClusterHub multiclusterhub: Failed to create object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Internal error occurred: failed calling webhook \\\"multiclusterhub.validating-webhook.open-cluster-management.io\\\": Post \\\"https://multiclusterhub-operator-webhook.hub.svc:443/validate-v1-multiclusterhub?timeout=10s\\\": EOF\",\"reason\":\"InternalError\",\"details\":{\"causes\":[{\"message\":\"failed calling webhook \\\"multiclusterhub.validating-webhook.open-cluster-management.io\\\": Post \\\"https://multiclusterhub-operator-webhook.hub.svc:443/validate-v1-multiclusterhub?timeout=10s\\\": EOF\"}]},\"code\":500}\n", "reason": "Internal Server Error", "status": 500}

---

No Cluster or Endpoint in the broker namespace on hub