---
- name: set default for state
  set_fact: 
    kubectl: /usr/local/bin/kubectl
  when: setState is not defined

- name: Namespaces and objects are being deleted from Managed Clusters
  ansible.builtin.debug:
    msg:
    - "Deletion of ManagedClusters cleans namespaces on the managed clusters- could take up to 15 minutes"

- name: Remove imported managed clusters from hub and wait 
  kubernetes.core.k8s:
    state: absent
    wait: yes
    wait_sleep: 30 # Check every 30 seconds
    wait_timeout: 2500
    context: "{{ hub_context }}"
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ item.name }}"
      spec:
        hubAcceptsClient: true
  loop: "{{ clusters }}"

- name: Remove klusterlet CRD yaml in files directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/roles/import-clusters/files/{{ item.name }}-klusterlet-crd.yaml"
    state: absent
  loop: "{{ clusters }}"

- name: Remove import yaml in files directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/roles/import-clusters/files/{{ item.name }}-import.yaml"
    state: absent
  loop: "{{ clusters }}"

- name: Pause before uninstalling ACM
  pause:
    seconds: 10


