---
- name: Remove imported managed clusters from hub
  kubernetes.core.k8s:
    state: absent
    context: hub
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ item.name }}"
      spec:
        hubAcceptsClient: true
  loop: "{{ clusters }}"
  
- name: Remove ManagedClusterSet from the hub
  kubernetes.core.k8s:
    state: absent
    context: hub
    definition:
      apiVersion: cluster.open-cluster-management.io/v1alpha1
      kind: ManagedClusterSet
      metadata:
        name: cockroachdb-clusterset
      spec: {}