---
- name: set default for kubectl
  set_fact: 
    kubectl: /usr/local/bin/kubectl
  when: kubectl is not defined

# - name: Check amount of clusters
#   include_role:
#     name: install-multi-cockroachdb
#     tasks_from: pre_validation

- name: Create submariner addon on-prem
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
      kind: SubmarinerConfig
      metadata:
          name: submariner
          namespace: "{{ item.name }}"
      spec: {}
  loop: "{{ clusters }}"
  when: item.cloud == "on-prem"

- name: Create secret for AWS credentials
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
          name: "{{ item.name }}-aws-creds"
          namespace: "{{ item.name }}"
      type: Opaque
      data:
          aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY') | b64encode }}"
          aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_KEY') | b64encode }}"
  loop: "{{ clusters }}"
  when: item.cloud == "aws"

- name: Register instance type for AWS
  shell: |
    "{{ kubectl }}" get nodes --context "{{ item.contexts }}" -l node-role.kubernetes.io/worker -ojsonpath='{.items[0].metadata.labels.beta\.kubernetes\.io/instance-type}'
  register: instance_type
  loop: "{{ clusters }}"
  when: item.cloud == "aws"

- name: Create submariner addon AWS
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
      kind: SubmarinerConfig
      metadata:
          name: submariner
          namespace: "{{ item.0.name }}"
      spec:
          gatewayConfig:
            aws:
              instanceType: "{{ item.1.stdout_lines[0] }}"
          credentialsSecret:
            name: "{{ item.0.name }}-aws-creds"
  with_together:
  -  "{{ clusters }}"
  -  "{{ instance_type.results }}"
  loop_control:
    index_var: my_idx
  when: item.0.cloud == "aws"


- name: Create secret for GCP credentials
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
          name: "{{ item.name }}-gcp-creds"
          namespace: "{{ item.name }}"
      type: Opaque
      data:
          osServiceAccount.json: "{{ lookup('env', 'OCP_SERVICE_ACCOUNT') | b64encode }}"
  loop: "{{ clusters }}"
  when: item.cloud == "gcp"

- name: Create submariner addon GCP
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
      kind: SubmarinerConfig
      metadata:
          name: submariner
          namespace: "{{ item.name }}"
      spec:
          credentialsSecret:
            name: "{{ item.name }}-gcp-creds"
  loop: "{{ clusters }}"
  when: item.cloud == "gcp"

- name: Deploy Submariner on the managed clusters
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: addon.open-cluster-management.io/v1alpha1
      kind: ManagedClusterAddOn
      metadata:
          name: submariner
          namespace: "{{ item.name }}"
      spec:
          installNamespace: submariner-operator
  loop: "{{ clusters }}"