---
# - name: Check amount of clusters
#   include_role:
#     name: install-multi-cockroachdb
#     tasks_from: pre_validation

- name: set default for clusterSet Name
  set_fact: 
    clusterset_name: clusterset1
  when: clusterset_name is not defined

- name: Create managed cluster set 
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: cluster.open-cluster-management.io/v1alpha1
      kind: ManagedClusterSet
      metadata:
        name: "{{ clusterset_name }}"

- name: Create rules for RBAC ClusterRole
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: clusterrole1
      rules:
        - apiGroups: ["cluster.open-cluster-management.io"]
          resources: ["managedclustersets/join"]
          resourceNames: ["{{ clusterset_name }}"]
          verbs: ["create"]

- name: Create the cluster set
  kubernetes.core.k8s:
    wait: yes
    state: present
    context: "{{ hub_context }}"
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ item.name }}"
        labels:
          cluster.open-cluster-management.io/clusterset: "{{ clusterset_name }}"
      spec:
        hubAcceptsClient: true
  loop: "{{ clusters }}"