---
- name: set default for clusterSet Name
  set_fact: 
    clusterset_name: clusterset1
  when: clusterset_name is not defined

- name: Remove managed cluster set 
  state: absent
  wait: yes
  kubernetes.core.k8s:
    state: absent
    context: hub
    definition:
      apiVersion: cluster.open-cluster-management.io/v1alpha1
      kind: ManagedClusterSet
      metadata:
        name: "{{ clusterset_name }}"

- name: Remove RBAC ClusterRole
  state: absent
  wait: yes
  kubernetes.core.k8s:
    state: absent
    context: hub
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: clusterrole1
      rules:
        - apiGroups: ["cluster.open-cluster-management.io"]
          resources: ["managedclustersets/join"]
          resourceNames: ["{{ clusterset_name }}"]
          verbs: ["create"]
