---
- name: Remove MultiClusterHub custom resource
  community.kubernetes.k8s:
    state: absent
    namespace: hub
    definition:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: hub
      spec:
        imagePullSecret: acm-test01-pull-secret # Variablize thus

- name: Delete Hub namespace objects # Can this be cleaned up?
  shell: |
    /usr/local/bin/kubectl delete deploy,sa,svc,pvc,pod,cm,secret --all -n hub

- name: Delete namespace for ACM (hub)
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: project.openshift.io/v1
      description: hub
      displayName: hub
      kind: Project
      metadata:
          name: hub

- name: Delete CRDs # Can this be cleaned up?
  shell: |
    /usr/local/bin/kubectl get crd | grep open-cluster-management.io | awk '{print $1}' | xargs /usr/local/bin/kubectl delete crd 